name: ketshop
description: Parents Choose. Kids Buy.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+42
build_date: 10/31/2022

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.13.3
  retry: ^3.1.0
  intl: ^0.17.0
  device_info_plus: ^3.1.1
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.4
  flutter_screenutil: ^5.0.0
  flutter_easyloading: ^3.0.0
  provider: ^6.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  flutter_html: ^3.0.0-alpha.3
  flutter_credit_card: ^3.0.1
  group_list_view: ^1.1.1
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.9.0
  wiredash: ^0.7.0+1
  flutter_staggered_grid_view: ^0.4.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.0
  firebase_analytics: ^9.0.3
  universal_html: ^2.0.8
  google_sign_in: ^5.2.1
  flutter_native_splash: ^2.1.6
  google_sign_in_web:
  sign_in_with_apple: ^4.0.0
  flutter_keychain: ^2.1.0
  package_info_plus: ^1.3.0
  custom_pop_up_menu:
    git:
        url: https://github.com/Ketshop/custom_pop_up_menu
  flutter_math_fork: ^0.6.2
  upgrader: ^4.1.0
  firebase_dynamic_links: ^4.0.3
  pin_code_fields: ^7.3.0
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  photo_view: ^0.14.0
  permission_handler: ^9.2.0
  share_plus: ^4.0.4
  flutter_facebook_auth: ^4.3.4+2
  image_picker: ^0.8.5+3
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.11
  path: ^1.8.1
  universal_io: ^2.0.4
  http_parser: ^4.0.1
  animations: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^0.8.1
  test: ^1.16.8

flutter_native_splash:
  #  color: "#000000"
  image: "assets/images/ketshop_white_text_splash.png"
  background_image: "assets/images/black_background.png"
  android: true
  ios: true
  web: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ketshop_white_bg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/images/3.0x/
    - pubspec.yaml
    #    - assets/images/avatars/
    #    - assets/images/categories/
    #    - assets/images/productCategories/
    - assets/images/social_media/
    - assets/images/welcome/
    - assets/dummy_json/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan/Spartan-Black.ttf
        - asset: assets/fonts/Spartan/Spartan-Bold.ttf
        - asset: assets/fonts/Spartan/Spartan-ExtraBold.ttf
        - asset: assets/fonts/Spartan/Spartan-ExtraLight.ttf
        - asset: assets/fonts/Spartan/Spartan-Light.ttf
        - asset: assets/fonts/Spartan/Spartan-Medium.ttf
        - asset: assets/fonts/Spartan/Spartan-Regular.ttf
        - asset: assets/fonts/Spartan/Spartan-SemiBold.ttf
        - asset: assets/fonts/Spartan/Spartan-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Regular.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
